to_do/urls.py
from django.urls import path
from to_do.views import (
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,

    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    toggle_status_task,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),

    path(
        "task/append/",
        TaskCreateView.as_view(),
        name="task-append",
    ),
    path(
        "task/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "task/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete",
    ),

    path(
        "task/<int:pk>/toggle-assign/",
        toggle_status_task,
        name="toggle-status-task",
    ),


    path(
        "tags/",
        TagListView.as_view(),
        name="tag-list",
    ),
    path(
        "tags/append/",
        TagCreateView.as_view(),
        name="tag-append",
    ),
    path(
        "tags/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update",
    ),
    path(
        "tags/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete",
    ),

]

app_name = "to_do"

todo_list_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("", include("to_do.urls", namespace="to_do")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

to_do/models.py
from django.db import models
from django.urls import reverse


class Tag(models.Model):
    name = models.CharField(max_length=63)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField(max_length=255)
    create = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(default=False)
    tags = models.ManyToManyField(
        Tag,
        related_name="tasks",
        blank=True
    )

    class Meta:
        ordering = ["status", "-create"]

    @staticmethod
    def get_absolute_url():
        return reverse('to_do:task-list')

    def __str__(self):
        return f"{self.content} {self.status} " \
               f"Create: {self.create}" \
               f"Tags: {self.tags}"

to_do/forms.py
from django import forms
from to_do.models import Tag, Task


class TaskCreationForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
        initial=0,
    )
    deadline = forms.DateTimeField(
        widget=forms.widgets.DateTimeInput(
            attrs={"type": "datetime-local"}
        ),
        required=False
    )

    class Meta:
        model = Task
        fields = ("content", "deadline", "tags")

to_do/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from to_do.forms import TaskCreationForm
from to_do.models import Tag, Task


class TagListView(generic.ListView):
    model = Tag
    paginate_by = 5
    queryset = Tag.objects.all()
    template_name = "to_do/tag_list.html"
    context_object_name = "tag_list"


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("to_do:tag-list")
    template_name = "to_do/tag_form.html"


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("to_do:tag-list")
    template_name = "to_do/tag_form.html"


class TagDeleteView(generic.DeleteView):
    model = Tag
    template_name = "to_do/tag_confirm_delete.html"
    success_url = reverse_lazy("to_do:tag-list")


class TaskListView(generic.ListView):
    model = Task
    queryset = Task.objects.all().prefetch_related("tags")
    paginate_by = 4


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskCreationForm
    success_url = reverse_lazy("to_do:task-list")
    template_name = "to_do/task_form.html"


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskCreationForm


class TaskDeleteView(generic.DeleteView):
    model = Task
    template_name = "to_do/task_confirm_delete.html"
    success_url = reverse_lazy("to_do:task-list")


def toggle_status_task(request, pk):
    task = Task.objects.filter(id=pk)
    task.update(status=True) if not Task.objects.get(id=pk).status else task.update(status=False)
    return HttpResponseRedirect(reverse_lazy("to_do:task-list"))

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
        <title>TODO List</title>
    {% endblock %}
    <meta charset="utf=8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    <div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2">

                    {% block sidebar %}
                        {% include "includes/sidebar.html" %}
                    {% endblock %}

                </div>

                <div class="col-sm-9">

                        {% block content %}{% endblock %}

                </div>

            </div>
        </div>
    </div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group" style="text-align: center">
    <li class="list-group-item"><a href="{% url 'to_do:task-list' %}"><strong> Home</strong></a></li>
    <li class="list-group-item"><a href="{% url 'to_do:tag-list' %}"><strong> Tags</strong></a></li>
</ul>

templates/to_do/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Delete Tag</h1>

    <p>Are you want to delete this Tag: {{ tag }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete" class="btn btn-danger"/>

        <a class="btn btn-primary" href="{% url 'to_do:tag-list' %}"> Cancel</a>
    </form>
{% endblock %}

templates/to_do/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>{{ object|yesno:"Update, Append" }} Tag</h1>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}

        <input class="btn btn-primary" type="submit" value="Submit">

        <a class="btn btn-primary" href="{% url 'to_do:tag-list' %}"> Cancel</a>
    </form>
{% endblock %}

templates/to_do/tag_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>
        Tags
        <a style="float: right; margin-top: 8px" class="btn btn-primary" href="{% url 'to_do:tag-append' %}"> Add</a>
    </h1>

    {% if tag_list %}
        <table class="table">
            <str>
                <tr>
                    <th>Name</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>

                {% for tag in tag_list %}
                    <tr>
                        <td>
                            {{ tag.name }}
                        </td>
                        <td>
                            <a class="btn btn-secondary" href="{% url 'to_do:tag-update' pk=tag.id %}">Update</a>
                        </td>
                        <td>
                            <a class="btn btn-secondary" href="{% url 'to_do:tag-delete' pk=tag.id %}">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
            </str>
        </table>
    {% else %}
        <p>The are no tag in list</p>
    {% endif %}

{% endblock %}

templates/to_do/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Delete Task</h1>

    <p>Are you want to delete this Task: {{ task.content }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete" class="btn btn-danger"/>

        <a class="btn btn-primary" href="{% url 'to_do:task-list' %}"> Cancel</a>
    </form>

{% endblock %}

templates/to_do/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}


{% block content %}
    <h1>{{ object|yesno:"Update, Append" }} Task</h1>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}

        <input class="btn btn-primary" type="submit" value="Submit">

        <a class="btn btn-primary" href="{% url 'to_do:task-list' %}"> Cancel</a>
    </form>
{% endblock %}

templates/to_do/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>
        TODO list
        <a style="float: right; margin-top: 8px" class="btn btn-primary" href="{% url 'to_do:task-append' %}"> Add task</a>
    </h1>
    <br>
    {% for task in task_list %}
        <h5>
            <strong>
                {{ task.content }}
                {% if task.status == False %}
                    <span style="color: red"> Not done</span>
                    <a style="float: right; margin-top: 8px" class="btn btn-success" href="{% url 'to_do:toggle-status-task' pk=task.id %}"> Complete</a>
                {% else %}
                    <span style="color: green"> Done</span>
                    <a style="float: right; margin-top: 8px" class="btn btn-secondary" href="{% url 'to_do:toggle-status-task' pk=task.id %}"> Undo</a>
                {% endif %}
            </strong>
        </h5>
        <p>
            Created: {{ task.create }}
            {% if task.deadline %}
                <span style="color: darkred"> Deadline: {{ task.deadline }}</span>
            {% endif %}
        </p>
        {% if task.tags.all %}
            <p class="text-muted"> Tags:
                {% for tag in task.tags.all %}
                    {{ tag }}
                {% endfor %}
                <a href="{% url 'to_do:task-update' pk=task.id %}"> Update</a>
                <a href="{% url 'to_do:task-delete' pk=task.id %}"> Delete</a>
            </p>
        {% endif %}
        <hr>

    {% empty %}
        <p>The are no task in list!</p>
    {% endfor %}

{% endblock %}